//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_PM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySQL_Prod : DbContext
    {
        public MySQL_Prod()
            : base("name=MySQL_Prod")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<category_dict> category_dict { get; set; }
        public virtual DbSet<producent> producents { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<sys_config> sys_config { get; set; }
        public virtual DbSet<vat_dict> vat_dict { get; set; }
    }
}
