//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI_PM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string EAN { get; set; }
        public int ProducentID { get; set; }
        public int CategoryID { get; set; }
        public int VATID { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }

        [ForeignKey(nameof(CategoryID))]
        public virtual category_dict category_dict { get; set; }
        [ForeignKey(nameof(ProducentID))]
        public virtual producent producent { get; set; }
        [ForeignKey(nameof(VATID))]
        public virtual vat_dict vat_dict { get; set; }
    }
}
